title: Virtual Seminar Series on Gaussian Processes, Spatiotemporal Modeling, and Decision-making Systems
description: An online seminar series to bring researchers working in Gaussian processes and related areas together
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
future: true
short_title: Gaussian Process Seminar Series
default_day: "Monday"
default_time: "16:00 UTC"
schedule_limit: 4
previous_limit: 3
header_menu:
    -
        title: "Home"
        link: "/#home"
    -
        title: "Current Seminar"
        link: "/#seminar"
    -
        title: "Schedule"
        link: "/#schedule"
    -
        title: "Previous Seminars"
        link: "/#previous"
defaults:
    - scope:
        path: "_posts/current"
      values:
        layout: post
        category: current
    - scope:
        path: "_posts/archive"
      values:
        layout: post
        category: archive
        